--------------------------------------------------------------------------------
-- Member 관련 테이블
--------------------------------------------------------------------------------
-- MEMBER 테이블 생성

CREATE TABLE MEMBER(  
    NO NUMBER PRIMARY KEY,
    id VARCHAR2(30) NOT NULL UNIQUE,
    role VARCHAR2(100) DEFAULT '일반회원' NOT NULL,
    email VARCHAR2(50) NOT NULL,
    password VARCHAR2(50) NOT NULL,
    name    VARCHAR2(30)    NULL,
    phone   VARCHAR2(13)    NULL,
    nickName VARCHAR2(50) NOT NULL,
    gender  VARCHAR2(1) NULL,
    age     NUMBER      NULL,
    address VARCHAR2(100) NOT NULL,
    enrollDate DATE DEFAULT SYSDATE NOT NULL,
    modifyDate DATE DEFAULT SYSDATE NULL,
    regular_delivery VARCHAR(1) DEFAULT 'N' NULL,
    status VARCHAR2(1) DEFAULT 'Y' CHECK( STATUS IN ('Y','N')),
    petName  VARCHAR(30),
    petBirth   VARCHAR(20),
    petType   VARCHAR2(40),
    petSort  VARCHAR2(40),
    petGender VARCHAR2(20),
    petNeutralization VARCHAR2(20),
    petConcern   VARCHAR2(200),
    emailAgree VARCHAR2(1) DEFAULT 'N',
    smsAgree VARCHAR2(1) DEFAULT 'N',
    terms1 VARCHAR2(1), 
    terms2 VARCHAR2(1)
);

CREATE SEQUENCE SEQ_UNO;

-- REGULAR_DELIVERY, STATUS, ROLE, ENROLLDATE 속성 수정
ALTER TABLE MEMBER MODIFY REGULAR_DELIVERY VARCHAR2(1) DEFAULT 'N' NULL ;
ALTER TABLE MEMBER MODIFY STATUS VARCHAR2(1) DEFAULT 'Y' NULL;
ALTER TABLE MEMBER MODIFY ROLE VARCHAR2(100) DEFAULT 'ROLE_USER' NULL;
ALTER TABLE MEMBER MODIFY ENROLLDATE DATE DEFAULT SYSDATE NULL;

-- 코멘트

COMMENT ON COLUMN MEMBER.ID IS '아이디';
COMMENT ON COLUMN MEMBER.ROLE IS '회원타입';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.PASSWORD IS '비밀번호';
COMMENT ON COLUMN MEMBER.NAME IS '이름';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.NICKNAME IS '닉네임';
COMMENT ON COLUMN MEMBER.GENDER IS '성별';
COMMENT ON COLUMN MEMBER.AGE IS '나이';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '정보수정일';
COMMENT ON COLUMN MEMBER.REGULAR_DELIVERY IS '정기배송';
COMMENT ON COLUMN MEMBER.STATUS IS '상태';

-- 관리자 정보 삽입

INSERT INTO MEMBER VALUES(
    'admin',
    '관리자',
    'abc@abcd.com',
    '1234',
    '관리자',
    '010-0000-0000',
    '관리자123',
    'M',
    26,
    '경기도 파주시',
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT
);

SELECT * FROM MEMBER;

COMMIT;


----------------------------------------------------------------------
-- Product 관련 테이블
----------------------------------------------------------------------
-- PRODUCT 테이블 생성
CREATE TABLE PRODUCT (
	PRODUCT_NO NUMBER PRIMARY KEY,
	PRODUCT_CAT_NO VARCHAR2(30),
	PRODUCT_NAME VARCHAR2(500),
	PRICE NUMBER DEFAULT 0,
	PRODUCT_AMOUNT NUMBER,
	ORIGINAL_FILENAME VARCHAR2(100),
    RENAMED_FILENAME VARCHAR2(100),
	PRODUCT_CONTENTS VARCHAR2(4000),
	PRODUCT_ENROLL_DATE DATE DEFAULT SYSDATE,
	PRODUCT_GRADE NUMBER DEFAULT 0,
	PRODUCT_STATUS VARCHAR2(1) DEFAULT 'Y'
);
-- PRODUCT 테이블에 정기배송가능유무 컬럼 추가(기본값 'N')
ALTER TABLE PRODUCT ADD REGULAR_DELIVERY_ATTR VARCHAR(1) DEFAULT 'N';
ALTER TABLE PRODUCT MODIFY PRODUCT_STATUS VARCHAR(1) DEFAULT 'Y';

-- 코멘트
COMMENT ON COLUMN PRODUCT.PRODUCT_NO IS '상품번호';
COMMENT ON COLUMN PRODUCT.PRODUCT_CAT_NO IS '카테고리No';
COMMENT ON COLUMN PRODUCT.PRODUCT_NAME IS '상품이름';
COMMENT ON COLUMN PRODUCT.PRICE IS '상품가격';
COMMENT ON COLUMN PRODUCT.PRODUCT_AMOUNT IS '상품재고';
COMMENT ON COLUMN PRODUCT.ORIGINAL_FILENAME IS '원본 상품사진파일명';
COMMENT ON COLUMN PRODUCT.RENAMED_FILENAME IS '서버에 저장된 상품사진파일명';
COMMENT ON COLUMN PRODUCT.PRODUCT_CONTENTS IS '상품설명';
COMMENT ON COLUMN PRODUCT.PRODUCT_ENROLL_DATE IS '상품등록일';
COMMENT ON COLUMN PRODUCT.PRODUCT_GRADE IS '상품의 별점';
COMMENT ON COLUMN PRODUCT.PRODUCT_STATUS IS '상품상태';
COMMENT ON COLUMN PRODUCT.REGULAR_DELIVERY_ATTR IS '정기배송해당상품유무';

CREATE SEQUENCE SEQ_PRODUCT_NO;

-- 상품정보 삽입
INSERT INTO PRODUCT VALUES(
    SEQ_PRODUCT_NO.NEXTVAL,
    '1111',
    'default 상품',
    '00000',
    55,
    '원본사진.png',
    '변경된사진.png',
    '상품설명입니다상품설명입니다상품설명입니다상품설명입니다',
    DEFAULT,
    DEFAULT,
    DEFAULT,
    DEFAULT
);

SELECT * FROM PRODUCT;

COMMIT;

------------------------------------------------
--------------- Board 관련 테이블 ---------------
------------------------------------------------
CREATE TABLE BOARD (	
    NO NUMBER,
    WRITER_NO NUMBER, 
	TITLE VARCHAR2(50), 
	CONTENT VARCHAR2(2000), 
	READCOUNT NUMBER DEFAULT 0, 
    STATUS VARCHAR2(1) DEFAULT 'Y',
    CREATE_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN BOARD.NO IS '게시글번호';
COMMENT ON COLUMN BOARD.WRITER_NO IS '게시글작성자';
COMMENT ON COLUMN BOARD.TITLE IS '게시글제목';
COMMENT ON COLUMN BOARD.CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD.READCOUNT IS '조회수';
COMMENT ON COLUMN BOARD.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '게시글올린날짜';

CREATE SEQUENCE SEQ_BOARD_NO;
COMMIT;
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, 1, '게시글 1',  '이 게시글은 영국에서 시작해서...', DEFAULT, 'Y', SYSDATE);

-------------------------------------------------
---------------- CART 관련 테이블 ----------------
-------------------------------------------------
CREATE TABLE CART (
	CART_NO	NUMBER PRIMARY KEY,--COMMENT '장바구니번호(순서?)'
	PRODUCT_NO NUMBER DEFAULT 0, --COMMENT '상품번호'
    PRODUCT_NAME VARCHAR2(100) DEFAULT 'default',--COMMENT '상품이름'
	CART_COUNT NUMBER DEFAULT 1, --COMMENT '상품수량'
	PRICE_SUM NUMBER DEFAULT 0,	-- '총 금액'
	FILENAME VARCHAR2(100) DEFAULT '',	--COMMENT '상품 대표이지미 경로',
	BUY_DATE DATE DEFAULT SYSDATE, --COMMENT '장바구니 등록날짜'
    REGULAR_DELIVERY_ATTR VARCHAR2(1) DEFAULT 'N',--COMMENT '정기배송상품유무',
	STATUS	VARCHAR2(1) DEFAULT 'Y'	NOT NULL	--COMMENT '주문&삭제된 상품은 N처리'
);
CREATE SEQUENCE SEQ_CART_NO;

DESC CART;

COMMIT;
------------------- 테스트 용 쿼리 문 -----------------------

--INSERT INTO CART VALUES(SEQ_CART_NO.NEXTVAL, 18, '상품', DEFAULT, 10000, 'filename.png', DEFAULT, DEFAULT, DEFAULT);

--SELECT * FROM CART;

--SELECT COUNT(*) FROM CART WHERE STATUS='Y';

--SELECT RNUM, CART_NO, PRODUCT_NO, PRODUCT_NAME, CART_COUNT, PRICE_SUM, FILENAME, REGULAR_DELIVERY_ATTR, STATUS 
--FROM ( 
--	SELECT ROWNUM AS RNUM, CART_NO, PRODUCT_NO, PRODUCT_NAME, CART_COUNT, PRICE_SUM, FILENAME, REGULAR_DELIVERY_ATTR, STATUS 
--    FROM (
--        SELECT  C.CART_NO, C.PRODUCT_NO, C.PRODUCT_NAME, C.CART_COUNT, C.PRICE_SUM, 
--        C.FILENAME, C.REGULAR_DELIVERY_ATTR, C.STATUS FROM CART C 
--            WHERE ( C.STATUS = 'Y') ORDER BY C.CART_NO DESC 
--        ) 
--    ) 
--WHERE RNUM BETWEEN ? and ?;

--SELECT * FROM CART C WHERE C.STATUS = 'Y' AND C.CART_NO=?;

--UPDATE CART SET CART_COUNT=(CART_COUNT+1) WHERE CART_NO=?;

--UPDATE CART SET PRICE_SUM=(CART_COUNT * PRICE_SUM) WHERE CART_NO=?;

--UPDATE CART SET STATUS='Y' WHERE CART_NO=1;